### ISSUE TITLE
corev-gcc pulp/xcorev extensions support

### ISSUE THREAD

**Issue by RTLhamster** [openhwgroup/corev-gcc#1]
Hi there,
I'm currently moving our RTL+software setup from RI5CY to CV32E40P.

With PULP GCC I got pulp extensions to work (`riscv32-unknown-elf-gcc -march=IMXpulpv2`), 
and I could see these custom instructions in the disassembly (`riscv32-unknown-elf-objdump  -Mmarch=IMXpulpv2`).

But with the COREV flow I'm having a hard time to verify that "cv." commands are actually used/included.
(If I use `riscv32-corev-elf-gcc -march=rv32im_xcorev`)
I also seems there is no suitable march option with riscv32-corev-elf-objdump anymore.

It would be interesting to know what is the actual support status of these xcorev/pulp extensions in corev-gcc.
Examples I found never used march option *_xcorev, for a reason?

Thanks for your help!

**Comment by jeremybennett** [comment]
Hi @RTLhamster,

Thanks for your interest.

CORE-V GCC is a project of the Open Hardware Group to develop a commercial grade GNU tool chain based on the latest versions of upstream GCC and binutils/GDB.  Ultimately this will be submitted upstream as a vendor specific variant.  It will support all the CV32E40P PULP extensions, with the exception of the PULP SIMD and bitmanip instructions, which are to be replaced in future CORE-V cores by their official upstream versions (P and B extensions).

This is a work in progress. At present there is support for many of the instructions in the assembler. The relevant `X` architecture extensions are documented in the gas manual.  The remainder of the instructions will follow in the near future.  GCC support will follow in due course - we are dependent on a CV32E40P simulator suitable for use with GCC regression testing before we can make the relevant commits.  This is in development using GVSoC.  We anticipate this project will complete later in 2021 or early 2022, depending on the resource available.

HTH

**Comment by RTLhamster** [comment]
Thanks for the reply @jeremybennett 

Just for clarification:
If I understood you correctly, currently there is no support for automatic insertion of cv. instruction by the corev-gcc?
...but it will follow (hopefully soon)

I'm very much looking forward to this feature

**Comment by jeremybennett** [comment]
Hi @RTLhamster That's a correct understanding.  We'd welcome your contributions if you'd like to get involved.  There is a monthly meeting of the Open Hardware Group Software Task Group, and then a mid-month meeting of just the GNU tools team.

We've actually done quite a lot of the GCC work - we were held up for lack of a suitable test platform, but that has just been solved this week.

**Comment by RTLhamster** [comment]
Thank you for your efforts!
Its better to give this work to experts, not too me :p
But I'm willing to test your release

**Comment by RTLhamster** [comment]
Hi @jeremybennett,
Is there any update on xcorev extension support?

**Comment by jeremybennett** [comment]
The extensions continued to be developed. You will see there are a number of PRs under review for the repository.

The easiest way to track progress is to attend either the weekly CORE-V GCC videoconferences or the monthly Software Task Group meetings, or follow the minutes of the Software Task Group meetings (they are on the mailing list and in the core-v-sw repository).
