### ISSUE TITLE
Latest release generates push/pop(from Zcmp extension) instructions the assembler finds illegal

### ISSUE THREAD

**Issue by silabs-mateilga** [openhwgroup/corev-gcc#15]
When trying to simulate the interrupt_test for cv32e40s, the latest toolchain (corev-openhw-gcc-centos7-20221031) generates push/pop/popret instructions which in the assembler triggers an error:

![image](https://user-images.githubusercontent.com/59358563/206472099-78606fd1-3b8c-4dfb-9b0b-43f2721cf81e.png)

steps to reproduce:

1. Check out [this](https://github.com/silabs-mateilga/core-v-verif/tree/zcmp_env_debug) branch of the core-v-verif repository 
2. Download the latest CORE-V [toolchain](https://www.embecosm.com/resources/tool-chain-downloads/#corev) from Embecosm(31/10/2022)
3. Set the following environment variables:
`CV_SW_TOOLCHAIN=/[PATH]/corev-openhw-gcc-centos7-20221031`
`CV_SW_PREFIX=riscv32-corev-elf-`
4. From /core-v-verif/cv32e40s/sim/uvmt/, run command
`make test TEST=interrupt_test SIMULATOR=[your sim] USE_ISS=NO`

**Comment by jeremybennett** [comment]
Thanks @silabs-mateilga. So I don't have to fire up the complete verification example, can you show the compiler/assembler commands that make is running. It looks like the assembler doesn't know it has the Zc* architectural features enabled. This could be an issue with the tool chain binary or with the configuration of make.

I will ask @NandniJamnadas to investigate

**Comment by silabs-mateilga** [comment]
@jeremybennett Here's an example from the log:
`/home/mateilga/software/corev-openhw-gcc-centos7-20221031/bin/riscv32-corev-elf-gcc -Os -g -static -mabi=ilp32 -march=rv32im_zba1p00_zbb1p00_zbc1p00_zbs1p00_zicsr_zca_zifencei_zcmp -Wall -pedantic  -c /work/mateilga/openhw/core-v-verif_40s/cv32e40s/bsp/handlers.S -o handlers.o`

And here's the call right before the errors:
`/home/mateilga/software/corev-openhw-gcc-centos7-20221031/bin/riscv32-corev-elf-gcc \
	 \
	-Os -g -static -mabi=ilp32 -march=rv32im_zba1p00_zbb1p00_zbc1p00_zbs1p00_zicsr_zca_zifencei_zcmp -Wall -pedantic  \
	 \
	-I ../../tests/asm \
	-I /work/mateilga/openhw/core-v-verif_40s/cv32e40s/bsp \
	-o /work/mateilga/openhw/core-v-verif_40s/cv32e40s/sim/uvmt/xrun_results/default/interrupt_test/0/test_program/interrupt_test.elf \
	-nostartfiles \
	/work/mateilga/openhw/core-v-verif_40s/cv32e40s/tests/programs/custom/interrupt_test/interrupt_test.c \
	-T /work/mateilga/openhw/core-v-verif_40s/cv32e40s/bsp/link.ld \
	 -L /work/mateilga/openhw/core-v-verif_40s/cv32e40s/sim/uvmt/xrun_results/default/interrupt_test/0/test_program/bsp \
	-lcv-verif
`

Is this all you need? Please let me know if there is anything more I can provide.

**Comment by jeremybennett** [comment]
Thanks @silabs-mateilga. I'll let @NandniJamnadas check she can reproduce this. She'll draw on the expertise of @simonpcook if needed to create new builds.

**Comment by silabs-hfegran** [comment]
This issue is not a toolchain specific issue, it is due to the use of `.option norvc` without turning support back on after the relevant sections. As of now, that has to be done by `.option push` and `.option pop` as there is currently no other way to reenable Zc*-instructions. 

~~That said, this issue masks another issue, which I am currently investigating and I will create a new issue to cover that.~~ edit: outdated compiler, this issue should now be resolved with a source code update

**Comment by silabs-mateilga** [comment]
Seems to be a non-issue, closing.
