### ISSUE TITLE
How should an out-of-range index be treated?

### ISSUE THREAD

**Issue by melonedo** [openhwgroup/corev-gcc#26]
The testsuite for CoreV SIMD instructions uniformly tests out-of-range bit indices (-32 and 31) for `cv.srl/sra/sll/extract/extractu/insert` and treats them as valid code. However, the spec restricts them to a very narrow range, should we treat them as invalid or undefined behavior?

**Comment by ChunyuLiao** [comment]
Can you help explain the problem a bit more? Or give an example? I'm trying to understand the situation, but I don't understand the question.

**Comment by melonedo** [comment]
For example, `cv.extractu.h t0, t1, -1` or equivalently `__builtin_riscv_cv_simd_extractu_h(a, -1)` (only the lowest bit of the immediate is useful) can be treated in several way:
- Error that `-1` is not valid;
- Ignore the high bits of `-1` and behave as if `-1` is `1` (also there is problem about how to handle negative numbers);
- Leave it undefined.

**Comment by melonedo** [comment]
I think we should follow the implementation of gdb-binutils and not discuss it here.
