### ISSUE TITLE
__builtin_riscv_cv_alu_addRN() builtin generate incorrect assemble operand

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-gcc#31]
As per the snapshot below, addRN builtin generates an incorrect assemble operand. a6 should be taken as Rd, but a3 is used. 

![image](https://user-images.githubusercontent.com/6898281/227076661-7042e227-3ea4-42b7-b37d-140db1f81ad9.png)

**Comment by jeremybennett** [comment]
@superflyers Thanks for this.  It's a bug in the instruction printing inside the CORE-V machine description.  @NandniJamnadas will fix it (it's not just this builtin).

**Comment by NandniJamnadas** [comment]
This issue has now been fixed under this branch [CV32E40Pv2 General ALU Fix with Rebase](https://github.com/NandniJamnadas/corev-gcc/tree/nj-fix-general-alu-patch). This fix is not ready for a pull request as this fix is on top of the upstream rebase without Zc* patches. I will release a pull request as soon as these Zc* patches are ready.
