### ISSUE TITLE
Conflict between spec and GCC of bit manipulation instructions

### ISSUE THREAD

**Issue by melonedo** [openhwgroup/corev-gcc#32]
Take `cv.bclr` for example. The testcase [cv-march-xcvbitmanip-compile-bclr.c](https://github.com/openhwgroup/corev-gcc/blob/08dd5f65b06b47af097b865ed3b185a60d4304b9/gcc/testsuite/gcc.target/riscv/cv-march-xcvbitmanip-compile-bclr.c) has:

```c
// source
// note that 200 == (6 << 5) + 8
  res1 = __builtin_riscv_cv_bitmanip_bclr (a, 200);
// check
/* { dg-final { scan-assembler-times "cv\.bclr\t\(\?\:t\[0-6\]\|a\[0-7\]\|s\[1-11\]\),\(\?\:t\[0-6\]\|a\[0-7\]\|s\[1-11\]\),6,8" 1 } } */
```

assumes the compiled instruction to be like `cv.bclr a0, a1, 6, 8`. That is, the lower 5 bits come *after* the higher 5 bits, or `cv.bclr rD, rs1, range[9:5], range[4:0]`.

However in the [OpenHW specification: CORE-V builtin names#PULP bit manipulation builtins (32-bit)](https://github.com/openhwgroup/core-v-sw/blob/c4a465dcbce9d08e435ff637a9f5475aa71e277f/specifications/corev-builtin-spec.md#uint32_t-__builtin_riscv_cv_bitmanip_bclr-uint32_t-i-uint16_t-range), the lower 5 bits come *before* the higher 5 bits:

> #### `uint32_t __builtin_riscv_cv_bitmanip_bclr (uint32_t i, uint16_t range)`
> Case a) range is a constant
> - result: `rD`
> - i: `rs1`
> - range[4:0]: `Is2` (5-bit unsigned value)
> - range[9:5]: `Is3` (5-bit unsigned value)
> 
> 
> _Generated assembler:_
> 
> Case a)
> ```gas
>         cv.bclr  rD,rs1,Is2,Is3
> ```

FYI, this could be due to a difference in the signature of `cv.bclr`, which is `cv.bclr rD, rs1, Is3, Is2` in [CORE-V Instruction Set Custom Extension#Bit Manipulation Operations](https://github.com/openhwgroup/cv32e40p/blob/e1d33c596b741f3bd042030effc93b32cba36276/docs/source/instruction_set_extensions.rst#bit-manipulation-operations) where the order of Is3 and Is2 is reversed.

**Comment by MaryBennett** [comment]
PR #33 Should fix this issue.

**Comment by NandniJamnadas** [comment]
This issue has now been fixed under this PR [Update operand order to match spec for bit manip instructions](https://github.com/openhwgroup/corev-gcc/pull/33). This fix is not ready to be merged as we are waiting on the clean up patches for Zc* for the upstream rebase. This issue will be closed when we have the upstream rebase.
