### ISSUE TITLE
GCC requires version number to be specified with architecture extensions

### ISSUE THREAD

**Issue by jeremybennett** [openhwgroup/corev-gcc#37]
With the latest released binaries (see https://www.embecosm.com/resources/tool-chain-downloads/#corev), it seems that the compiler requires version numbers to be specified with the CORE-V extension name.  For example:
```
    /home/schiavon/tools/corev-riscv/bin/riscv32-corev-elf-gcc   -g -march=rv32imac_ziscr_xcvmem_xcvhwlp_xcvalu_xcvbi_xcvmac_xcvelw_xcvbitmanip_xcvsimd -g -march=rv32imac_ziscr_xcvmem_xcvhwlp_xcvalu_xcvbi_xcvmac_xcvelw_xcvbitmanip_xcvsimd    -o CMakeFiles/cmTC_83683.dir/testCCompiler.c.obj   -c /home/schiavon/gitdir/davide_obi_fifo/x-heep/sw/build/CMakeFiles/CMakeTmp/testCCompiler.c
    Assembler messages:
    Error: rv32imac_ziscr_xcvalu_xcvbi_xcvbitmanip_xcvelw_xcvhwlp_xcvmac_xcvmem_xcvsimd: unknown prefixed ISA extension `ziscr'
```
Instead you have to use
```
rv32imc_zicsr_zifencei_xcvhwlp1p0_xcvmem1p0_xcvmac1p0_xcvbi1p0_xcvalu1p0_xcvsimd1p0_xcvbitmanip1p0
```
Version numbers should default and in any case there is only one version!

**Comment by NandniJamnadas** [comment]
This issue has been fixed under `CORE-V: Remove versioning support for XCV Extensions` PR: GCC [#45](https://github.com/openhwgroup/corev-gcc/pull/45) and Binutils [#94](https://github.com/openhwgroup/corev-binutils-gdb/pull/94).

**Comment by NandniJamnadas** [comment]
@jeremybennett This issue has been fixed as the comment stated above. This issue can be closed now.
