### ISSUE TITLE
zcee needs zba and zbb

### ISSUE THREAD

**Issue by Liaoshihua** [openhwgroup/corev-gcc#4]
Hi, @jessicamills 

   In zcee, **zext.*** and **sext.*** 's instructions needs the B-extension subsets **Zba** and **Zbb** . I had not found them in corev-gcc .

I want to know how to solve this problem.

Thanks
Liao Shihua

**Comment by jessicamills** [comment]
Hi @Liaoshihua,

The CORE-V GCC development branch is based on upstream GCC top-of-tree. I believe B extensions are experimental and not in upstream GCC yet (see: https://wiki.riscv.org/display/TECH/RISC-V+extension+and+feature+support).

**Comment by jessicamills** [comment]
We have a meeting later today, I think this would be a good time to discuss how to solve this - I will add it to the agenda.

Thanks
