### ISSUE TITLE
__builtin_riscv_cv_bitmanip_insert generate incorrect operand

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-gcc#40]
Toolchain version: corev-openhw-gcc-centos7-20230504

Problem Statement:  

In the generated code of __builtin_riscv_cv_bitmanip_insert, value of l2 and l3 is swapped.  Initially, I thought it is an implementation issue, later I realized it looks more like a spec inconsistency issue.  as you can see below. two different cv.insert templates are given for two documents.

1) In corev instruction manuel 

<html>
<body>

cv.insert rD, rs1, Is3, Is2 | rD[min(Is3+Is2,31):Is2] = rs1[Is3-(max(Is3+Is2,31)-31):0]The rest of the bits of rD are untouched and keep their previous value.Is3 + Is2 must be < 32.
-- | --

</body>
</html>

2) in builtin spec

uint32_t __builtin_riscv_cv_bitmanip_insert (uint32_t i, uint16_t range, uint32_t  k)
Case a) range is a constant and (range[9:5] + range [4:0]) <= 32

result, k: rD
i: rs1
range[4:0]: Is2 (5-bit unsigned value)
range[9:5]: Is3 (5-bit unsigned value)
or case b)

result, k: rD
i: rs1
range: rs2
Generated assembler:

Case a)

        cv.insert  rD,rs1,Is2,Is3

**Comment by pascalgouedo** [comment]
This cv. insert rD, rs1, Is3, Is2 order is coming from RI5CY/PULP original specification and didn't change for CV32E40Pv2 in both User Manual and RTL.
This immediate order is the same for all ALU Bit Manipulation instructions.

Unfortunately this order swap was not seen during the builtin spec review.

**Comment by melonedo** [comment]
Related: #32 and #33.

**Comment by jeremybennett** [comment]
Thanks @superflyers 

This is something very much for you to advise on. We have three choices, all of which are easy enough to implement.
1. do nothing
2. update the builtin spec to change which bitfields in "range" correspond to Is2 and Is3
3. update the builtin spec to change the instruction generated

If we want to change the builtin spec, now is the time to do it, before we have a large user base.  I am inclined to the 3rd approach, because it will clearly match the hardware spec, but this is for you to advise.

**Comment by pascalgouedo** [comment]
Hi @jeremybennett 

Yes sure better to align all specs to the User Manual.
Go for 3rd option.

Regards,
Pascal.

**Comment by superflyers** [comment]
Thank you. Fully support 3rd option as well.

pascalgouedo ***@***.***> 于 2023年6月2日周五 16:42写道：

**Comment by jeremybennett** [comment]
Following the meeting of the OpenHW Group SW TG, we will start work on a revision of the builtin specification, and adopt approvach 3 above.  In the light of this, marking as a bug, and assigning to @MaryBennett to fix.

**Comment by NandniJamnadas** [comment]
This issue has been fixed under PR: [#33](https://github.com/openhwgroup/corev-gcc/pull/33) Update operand order to match spec for bit manip instructions and [#45](https://github.com/openhwgroup/corev-gcc/pull/45) CORE-V: Bit Manipulation bitrev builtin update.
