### ISSUE TITLE
How should IDEs gain awareness of Builtins?

### ISSUE THREAD

**Issue by NandniJamnadas** [openhwgroup/corev-gcc#48]
To make this user friendly it would be nice to include a header file for all the builtins that have been implemented.

- [x]  alu
- [x]  mac
- [x]  hwlp
- [x]  elw
- [x]  bi
- [x]  mem
- [x]  bitmanip
- [x]  simd

**Comment by MaryBennett** [comment]
LLVM PR: https://github.com/openhwgroup/corev-llvm-project/pull/88

Actions to bring this to conclusion:
1. @MaryBennett provide a patch for GCC
2. @PaoloS02 coordinate with the CORE-V IDE team to test the patch for GCC (and LLVM)

**Comment by MaryBennett** [comment]
Header for alu has been merged.

**Comment by MaryBennett** [comment]
All headers have been merged.
