### ISSUE TITLE
Toolchain flags errors for xpulp SIMD ALU instuctions cv.or.sci, cv.xor.sci, cv.and.sci with negative (signed) Imm6 operand

### ISSUE THREAD

**Issue by dd-vaibhavjain** [openhwgroup/corev-gcc#49]
## Toolchain release: 
corev-openhw-gcc-centos7-20230623

## Issue Description

**SIMD ALU operations  
**cv32e40p-user-manual-en-cv32e40p_v1.3.2.pdf , Table 7.31 SIMD ALU operations****

> cv.or.sci.h/b  
> cv.xor.sci.h/b  
> cv.and.sci.h/b  

User Manual description:  

> cv.or[.sc,.sci]{.h,.b} rD, rs1, [rs2, Imm6] rD[i] = rs1[i] | op2[i] 
> cv.xor[.sc,.sci]{.h,.b} rD, rs1, [rs2, Imm6] rD[i] = rs1[i] ^ op2[i] 
> cv.and[.sc,.sci]{.h,.b} rD, rs1, [rs2, Imm6] rD[i] = rs1[i] & op2[i]

For these instructions' [.sci] or immediate Scalar replication mode, with Imm6 used as scalar operand2, the User Manual currently does not explicitly specify whether the Imm6 operand is "Zero-extended", so in such cases as per the description of [.sci] mode in the user manual, these instructions should consider this immediate operand to be sign-extended and as such the signed decimal notation used in assembly for these cases should be allowed (in-line with other sign-extended instructions in this SIMD ALU instructions category).  

But with this release of toolchain, if the Imm6 field is negative decimal notation, the toolchain flags these as errors.  
Error Example:  

> cv.or.sci.b          t2, t2, -3
> Error: immediate value must be 6-bit unsigned, -3 is out of range
> 
> cv.and.sci.h         a6, s11, -24
> Error: immediate value must be 6-bit unsigned, -24 is out of range
> 
> cv.xor.sci.h         t1, s11, -13
> Error: immediate value must be 6-bit unsigned, -13 is out of range

**Comment by NandniJamnadas** [comment]
Hi @dd-vaibhavjain, thanks for raising this issue. I have fixed this issue in this pull request [#97](https://github.com/openhwgroup/corev-binutils-gdb/pull/97) CORE-V: SIMD Update: Updated cv.or.sci[.h,.b], cv.xor.sci[.h,.b], cv.and.sci[.h,.b] from unsigned to signed. It seems like the implementation for these instructions for the builtins are correct. Please let me know if you have any concerns with the corresponding builtins.

**Comment by pascalgouedo** [comment]
Hi,

The User Manual explicitly states following sentences at the beginning of SIMD section:

> 3. Immediate scalar replication mode (.sci), vector-scalar operation.
>    Operand 1 is treated as vector, while operand 2 is treated as a
>    scalar and comes from a 6-bit immediate.
> 
>    The immediate is either sign- or zero-extended depending on the operation.
>    If not specified, the immediate is sign-extended with the exception
>    of all cv.shuffle* where it is always unsigned.
> 
>    e.g. cv.add.sci.h x3,x2,0x2A performs:
> 
>     x3[31:16] = x2[31:16] + 0xFFEA
> 
>     x3[15: 0] = x2[15: 0] + 0xFFEA

As figured out with [#85](https://github.com/openhwgroup/corev-binutils-gdb/issues/85), hexadecimal values can't be used.
So I will change the User Manual example with 

>    e.g. cv.add.sci.h x3,x2,-22 performs:
>
>     x3[31:16] = x2[31:16] + 0xFFEA
> 
>     x3[15: 0] = x2[15: 0] + 0xFFEA

Best regards,
Pascal.

**Comment by dd-vaibhavjain** [comment]
> Hi @dd-vaibhavjain, thanks for raising this issue. I have fixed this issue in this pull request [#97](https://github.com/openhwgroup/corev-binutils-gdb/pull/97) CORE-V: SIMD Update: Updated cv.or.sci[.h,.b], cv.xor.sci[.h,.b], cv.and.sci[.h,.b] from signed to unsigned. It seems like the implementation for these instructions for the builtins are correct. Please let me know if you have any concerns with the corresponding builtins.

Hi @NandniJamnadas ,
Thanks for fixing this issue!

**Regarding the builtins :**
I am referring to https://github.com/openhwgroup/core-v-sw/blob/master/specifications/corev-builtin-spec.md  
(Please do correct me if am not referring correct/latest documention for builtins).   

And also do note that for the issue raised above, I did not use the builtin functions, I am rather using simulation environment to generate the assembly instructions directly for our verification tests.  

Here referring this builtin-spec, also it seems to me that the implementation is **_not fully correct_**:  

For example:

> int32_t __builtin_riscv_cv_simd_or_sc_h (uint32_t i, uint16_t j)

> Argument/result mapping:
> 
> Case a) j is a constant in the range 0 <= j <= 63
> result: rD
> i: rs1
> j: Is2 (6-bit unsigned value)

> or case b)
> result: rD
> i: rs1
> j: rs2
> Generated assembler:
> 
> Case a)
> 
>         cv.or.sci.h  rD,rs1,Is2
> or case b)
> 
>         cv.or.sc.h  rD,rs1,rs2

That means the 2nd argument for these builtin functions, is expected to be an unsigned value always even for **.sci** case with Immediate operand, whereas we wanted a signed Immediate to also be allowed as well.  

Same issue for builtins for cv.xor.sc{i}.{h/b} and cv.and.sc{i}.{h/b}.  

I believe as long as the register is used as operand the input argument being signed or unsigned does not matter for the final generated assembly, but it will surely be a problem for Immediate case.

**Comment by NandniJamnadas** [comment]
Hi @dd-vaibhavjain,

I have checked the builtin implementation for `cv.or.sc{i}.{h/b}`, `cv.xor.sc{i}.{h/b}` and `cv.and.sc{i}.{h/b}` in CORE-V GCC and it looks like it is currently using signed half integer (HI) and quarter integer (QI) respectively. This means the documentation needs updating. I will also add a pull request for this. Please let me know if you are having any issues with these builtins.

**Comment by dd-vaibhavjain** [comment]
Thanks @NandniJamnadas for confirming. Currently builtins are not directly used in cv32e40p core RTL verification testbench level as it is out of verification scope. But probably something to consider if we can also make use of these builtins here.

I just have a question related to this, if we want to use these builtin functions, at the moment we can get all the functions here from this [corev-builtin-spec.md](https://github.com/openhwgroup/core-v-sw/blob/master/specifications/corev-builtin-spec.md) spec. 
But since you mentioned the documentation is not updated here, meaning the actual generated may differ at times, so is there a final C-header type file (only function description) generated file available to check the actual generated API's of these builtin functions?

**Comment by NandniJamnadas** [comment]
> I just have a question related to this, if we want to use these builtin functions, at the moment we can get all the functions here from this [corev-builtin-spec.md](https://github.com/openhwgroup/core-v-sw/blob/master/specifications/corev-builtin-spec.md) spec. But since you mentioned the documentation is not updated here, meaning the actual generated may differ at times, so is there a final C-header type file (only function description) generated file available to check the actual generated API's of these builtin functions?

We are currently looking into the idea of implementing a C-header file so that users are aware of the builtins currently implemented. Right now all the documentation on builtins are in `gcc/doc/extend.texi` however this might not be so user friendly.

I have raised an issue under [#48](https://github.com/openhwgroup/corev-gcc/issues/48) How should IDEs gain awareness of Builtins. It would be great for anyone to drop in comments and opinions on the matter.

**Comment by MaryBennett** [comment]
@dd-vaibhavjain 
I believe the matters here are now addressed. 
1. @pascalgouedo is clarifying the documentation
2. #48 will track IDE support
I propose closing this issue. Please reopen if there is anything missed or raise a new issue.
Thank you for your contribution.
