### ISSUE TITLE
CORE-V: SIMD Constraints "CV6" and "CS6" needs renaming

### ISSUE THREAD

**Issue by NandniJamnadas** [openhwgroup/corev-gcc#53]
The naming of the constraints is confusing.

Currently implemented as
`CV6`: Signed 6 bit constant
`CS6`: Unsigned 6 bit constant
The naming of constraints is tricky - 1 or 2 characters and 1 digit, so there isn't much choice. But using S for "Unsigned" seems to be asking for confusion.

The naming for all CORE-V predicates and constraints may need renaming to keep with consistency. Would be nice to come up with a rule for naming constraints so that it is universally understandable. This may also apply to renaming CORE-V operands to correspond to the instruction rather than order e.g. currently implemented `b5` and `b8` correspond to signed and unsigned 6-bit immediate.

**Comment by NandniJamnadas** [comment]
This issue was raised within the pull request: [#52](https://github.com/openhwgroup/corev-gcc/pull/52) CORE-V: SIMD Update: cv.avgu.sc{i}[.h,.b] builtins from signed to unsigned.

**Comment by MaryBennett** [comment]
I suggest CS6 for signed 6-bit and CU6 for unsigned 6-bit.

**Comment by MaryBennett** [comment]
This issue has been solved via the rebase.
