### ISSUE TITLE
CORE-V: SIMD __builtin_riscv_cv_simd_neg_h and __builtin_riscv_cv_simd_neg_b needs implementing

### ISSUE THREAD

**Issue by NandniJamnadas** [openhwgroup/corev-gcc#54]
This is not an issue but a reminder that the SIMD neg puesdo builtin needs to be implemented to match the builtin specification: https://github.com/openhwgroup/core-v-sw/blob/master/specifications/corev-builtin-spec.md

**Comment by MaryBennett** [comment]
Corresponding patch merged
