### ISSUE TITLE
Update naming for xcvmem instructions

### ISSUE THREAD

**Issue by MaryBennett** [openhwgroup/corev-gcc#60]
Update instruction names to match documentation.

Corresponding Binutils issue: https://github.com/openhwgroup/corev-binutils-gdb/issues/101

ARM-like
Pre-*	cv.lw rd, (rs1, +/- imm/rs2)!
Post-*	cv.lw rd, (rs1), +/-imm/rs2

**Comment by pascalgouedo** [comment]
Hi @MaryBennett 
There are no pre-incremented instructions right now, just the post ones.

**Comment by pascalgouedo** [comment]
For per-* ones, I think I made a mistake and to be really ARM-like, a comma should be added after register name in the parenthesis.

Pre-* cv.lw rd, (rs1, +/- imm/rs2)!

**Comment by MaryBennett** [comment]
Corresponding pull request has been merged
