### ISSUE TITLE
latest released (02/Aug) gcc toolchain generates incorrect code.

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-gcc#61]
![image](https://github.com/openhwgroup/corev-gcc/assets/6898281/9b0d0594-0b43-43dd-8a9e-cf37ed58416f)

**Comment by MaryBennett** [comment]
Thank you for finding this, @superflyers 
Non-CORE-V normal reg+imm load/stores were prevented from being generated by under restrictive conditions for the CORE-V normal reg+reg load/stores.
This has been fixed in PR #62.

**Comment by MaryBennett** [comment]
Corresponding pull request has been merged
