### ISSUE TITLE
illegal operand error for "sw" operation

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-gcc#64]
affected the version pre-released at 20230814

/libs/dsp/src/TransformFunctions/dd_dct2_f32.c' -- 'dd_dct2_f32.o'
/tmp/ccAhyHfb.s: Assembler messages:
/tmp/ccAhyHfb.s:75: Error: illegal operands `sw a5,(a6),4'
/tmp/ccAhyHfb.s:90: Error: illegal operands `sw a5,(a6),4'
/tmp/ccAhyHfb.s:106: Error: illegal operands `sw a5,(a3),4'
/tmp/ccAhyHfb.s:174: Error: illegal operands `sw a0,(a3),4'

**Comment by jeremybennett** [comment]
@superflyers Thanks for picking this up.  Is this the change in post-inc syntax? Assigning to @MaryBennett to investigate further.

Do you have a trivial reproducer you can shared?

**Comment by MaryBennett** [comment]
The corresponding patch has been merged: #66.
