### ISSUE TITLE
How to check COREV_CLUSTER for Event Load Instruction

### ISSUE THREAD

**Issue by ChunyuLiao** [openhwgroup/corev-gcc#67]
This is a question from llvm https://github.com/openhwgroup/corev-llvm-project/issues/76

I'd like to learn how gcc implements this feature

Event Load Instruction
The event load instruction cv.elw is only supported if the COREV_CLUSTER parameter is set to 1. 

But how does the compiler detect the COREV_CLUSTER parameter.
or
The compiler does not require special checking and the user controls whether this extension is enabled or not？

ref:
https://github.com/openhwgroup/cv32e40p/blob/master/docs/source/instruction_set_extensions.rst#event-load-instruction

thanks

**Comment by pascalgouedo** [comment]
rv32_xcvelw if I remember correctly.

**Comment by MaryBennett** [comment]
Marking as closed
