### ISSUE TITLE
unrecognized opcode 'csrr' extension 'zicsr' required

### ISSUE THREAD

**Issue by promodkumar-ashling** [openhwgroup/corev-gcc#70]
Getting following error when building the cli_test sample project of CORE-V-SDK with latest [toolchain(15th Aug 2023),](https://www.embecosm.com/resources/tool-chain-downloads/#corev) it seems  latest toolchain doesn’t have the support for the pseudo instruction ‘csrr’.

![image](https://github.com/openhwgroup/corev-gcc/assets/69203453/94dd030a-ed98-4822-a812-3eca6ec56e40)

**Comment by jeremybennett** [comment]
@promodkumar-ashling Thanks for raising.  Can I check you are specifying `zicsr` in the `-march` string. It used to be implicit, but in recent tool chains has to be specified explicitly.

**Comment by jeremybennett** [comment]
@promodkumar-ashling Can you provide the pre-processed test case (compile with --save-temps and attach the .i file), and the command used to compile it.  With a reproducer we can track this down.

**Comment by jeremybennett** [comment]
Added @MaryBennett to investigate.

**Comment by simonpcook** [comment]
This is the issue where where when the RISC-V Base Instruction Sets were ratified, the CSR instructions were removed and placed into their own extension `zicsr`, and our GCC build defaults to this updated version of the base instruction sets/etc.

I see above a reference to Ubuntu 22.04 specifically being an issue... all the tools should be behaving the same, did this change at some point. I can check that against whether some rebase happened between versions.

**Comment by PaoloS02** [comment]
This issue is a bit old now. I'd leave it around for another week for any quick feedback or follow-up and then I'd close it. If needed it can be reopened afterwards.

**Comment by MaryBennett** [comment]
Closing this issue. If the problem remains, please reopen the issue.
