### ISSUE TITLE
illegal operands `flw fa5,t2(s1) is generated from the latest release toolchain (05/Sep)

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-gcc#73]
[gcc_73.zip](https://github.com/openhwgroup/corev-gcc/files/12679454/gcc_73.zip)

**Comment by MaryBennett** [comment]
ARCH: rv32imfc_zicsr_zifencei_xcvmem1p0_xcvmac1p0_xcvbi1p0_xcvalu1p0_xcvsimd1p0_xcvbitmanip1p0_xcvelw1p0
YES: ```flw rd, imm, (rs1)```
NO: ```flw rd, rimm. (rs1)```

movSI_internal [5/9]

op1 is a mem (plus rimm rs1) => ADDRESS_REG

If predicate ```mem_plus_reg``` was true for op1, ```move_operand``` & ```movSI``` would be false.

There are no non-post-inc reg:reg load/store outside of CORE-V.

**Comment by MaryBennett** [comment]
Fixed in PR #75
