### ISSUE TITLE
Incorrect code generation with PULP march with 20231017 release

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-gcc#77]
When compiling Embench tests, following errors are reported:

### march=rv32imc_zicsr_zifencei_xcvmem_xcvmac_xcvbi_xcvalu_xcvsimd_xcvbitmanip

- sglib-combined
Assembler messages:
Error: illegal operands `sb zero,a2(a5)'
- st
error: unrecognizable insn:
133 | }
       | ^
(insn 13 12 14 4 (set (reg:DF 12 a2)
        (mem:DF (plus:SI (reg/v/f:SI 140 [ Array ])
                (reg:SI 143)) [2 MEM[(double *)Array_16(D) + _9 * 1]+0 S8 A64])) "embench/src/st/libst.c":131:10 -1
     (nil))
during RTL pass: vregs
embench/src/st/libst.c:133:1: internal compiler error: in extract_insn, at recog.cc:2791

**Comment by MaryBennett** [comment]
Fixed in PR #81
