### ISSUE TITLE
Hardware Loops march option not recognized

### ISSUE THREAD

**Issue by pascalgouedo** [openhwgroup/corev-gcc#78]
When compiling Embench tests, following error is reported:

riscv32-corev-elf-gcc: error: '-march=rv32imc_zicsr_zifencei_xcvhwlp_xcvmem_xcvmac_xcvbi_xcvalu_xcvsimd_xcvbitmanip': extension 'xcvhwlp' starts with 'x' but is unsupported non-standard extension

**Comment by MaryBennett** [comment]
Fixed in issue #80
