### ISSUE TITLE
cannot find suitable multilib during the build, though it is shown in the toolchain lib folder.

### ISSUE THREAD

**Issue by superflyers** [openhwgroup/corev-gcc#90]
When I’m trying to build another test with the new toolchain. I encountered the issue below.

 
![image](https://github.com/openhwgroup/corev-gcc/assets/6898281/4d17599c-c6e4-46ac-bf3f-d63abbf4cb96)

This is the prebuild lib I saw in the toolchain folder.

![image](https://github.com/openhwgroup/corev-gcc/assets/6898281/acdec80f-9787-4ffb-b895-31d74a56399f)

Here are the compiler option used:

LAST_CC = /share/libraries/LIBRARY/0TECHNO/EMBECOSM/TOOLCHAIN/corev-openhw-gcc-centos7-20231128/bin/riscv32-corev-elf-gcc
LAST_CFLAGS = -D__RISCV_CV32__ -D__RISCV_GENERIC__ -DPANTHER -DPANTHER -DWITH_ALLOC -DRTOS_PMSIS -DCLUSTER_COMPILATION -DIS_NOT_VEP -I/scorpion/home/lch/project/panther_release/last/libs/dsp/include -I/drivers/include -fdata-sections -ffunction-sections -DARCHI_CLUSTER_NB_PE=16 -DCLUSTER_COMPILATION -MMD -march=rv32imc_zicsr_zfinx_xcvalu_xcvbi_xcvbitmanip_xcvhwlp_xcvmac_xcvmem_xcvsimd_xcvelw -Wall -Wextra -Wno-unused-variable -Wno-unused-parameter -fdata-sections -fno-common -msmall-data-limit=0 -ffunction-sections -DWITH_ALLOC -Wno-missing-field-initializers -g -O3 -DPRINTF_FLOAT -DMEASUREMENT -I.
LAST_LDFLAGS = -march=rv32imc_zicsr_zfinx_xcvalu_xcvbi_xcvbitmanip_xcvhwlp_xcvmac_xcvmem_xcvsimd_xcvelw -Wl,--gc-sections -Wl,-Map=/net/eagle/volume1/homes/lch/project/examples/dsp/mfcc_f32/build.riscv_vp/panther/build/output.map -static -nostdlib -lm -lgcc

**Comment by MaryBennett** [comment]
@simonpcook Does this require a change to the build scripts?

**Comment by MaryBennett** [comment]
AP: remove _zicsr for multilibs

**Comment by MaryBennett** [comment]
@superflyers Is this issue fixed?

**Comment by MaryBennett** [comment]
Closing issue. Please open a new one if the issue reoccurs.
